version: "3.8"
services:
  database:
    image: "postgres:14-alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=marketplace_app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=marketplace_app_development
    volumes:
      - postgres_data_development:/var/lib/postgresql/data

  redis:
    image: "redis:7"
    ports:
      - 6379:6379

volumes:
  postgres_data_development: {}
